import { ImageResponse } from 'next/og'
import { readFile } from 'node:fs/promises'
import { join } from 'node:path'

export const runtime = 'nodejs'              // MUST be nodejs — Edge cannot use node:fs
export const size = { width: 180, height: 180 }
export const contentType = 'image/png'

/**
 * Renders the Quibs mascot (Q-face + two eye-dots) on the brand teal background
 * for iOS home-screen saves and social-share apple-touch-icon consumers.
 *
 * Source asset: public/quibs-icon.png (360×360, transparent bg, white mascot —
 * generated by scripts/rasterize-mascot.mjs from public/quibs-icon.svg).
 *
 * WHY PNG NOT SVG: see app/icon.tsx and 05-05-SUMMARY.md.
 */
export default async function AppleIcon() {
  const mascotPng = await readFile(join(process.cwd(), 'public/quibs-icon.png'))
  const mascotDataUri = `data:image/png;base64,${mascotPng.toString('base64')}`

  return new ImageResponse(
    (
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          width: '100%',
          height: '100%',
          background: '#14a3a3',
        }}
      >
        <img
          src={mascotDataUri}
          alt=""
          width={130}
          height={130}
          style={{ width: 130, height: 130 }}
        />
      </div>
    ),
    { ...size }
  )
}
