import { ImageResponse } from 'next/og'
import { readFile } from 'node:fs/promises'
import { join } from 'node:path'

export const runtime = 'nodejs'              // MUST be nodejs — Edge cannot use node:fs
export const size = { width: 32, height: 32 }
export const contentType = 'image/png'

/**
 * Renders the Quibs mascot (Q-face + two eye-dots) on the brand teal background.
 *
 * Source asset: public/quibs-icon.png (360×360, transparent bg, white mascot —
 * generated by scripts/rasterize-mascot.mjs from public/quibs-icon.svg).
 *
 * WHY PNG NOT SVG: Satori (the renderer behind next/og's ImageResponse) does not
 * support <img src=data:image/svg+xml;...> in @vercel/og 0.11.x. PNG via data URI
 * is supported. See app/opengraph-image.tsx and 05-05-SUMMARY.md for context.
 */
export default async function Icon() {
  const mascotPng = await readFile(join(process.cwd(), 'public/quibs-icon.png'))
  const mascotDataUri = `data:image/png;base64,${mascotPng.toString('base64')}`

  return new ImageResponse(
    (
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          width: '100%',
          height: '100%',
          background: '#14a3a3',
        }}
      >
        <img
          src={mascotDataUri}
          alt=""
          width={22}
          height={22}
          style={{ width: 22, height: 22 }}
        />
      </div>
    ),
    { ...size }
  )
}
