// AUTO-GENERATED by scripts/generate-consent-version.mjs — do not edit.
// Regenerated at build time from app/(legal)/privacy/page.tsx and
// app/(legal)/terms/page.tsx. See lib/consent-version.ts for context.
export const CONSENT_VERSION = 'bd9e3ddd' as const
